### ISSUE TITLE
[engine:rococoa] what's this?

### ISSUE THREAD

**Issue by umjammer** [umjammer/vavi-speech2#5]
non blocking issue

```
org.rococoa.RococoaException: Exception calling method for selector speechSynthesizer:willSpeakWord:ofString:
	at org.rococoa.internal.OCInvocationCallbacks.callMethod(OCInvocationCallbacks.java:169)
	at org.rococoa.internal.OCInvocationCallbacks.access$200(OCInvocationCallbacks.java:52)
	at org.rococoa.internal.OCInvocationCallbacks$1.callback(OCInvocationCallbacks.java:80)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:585)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:616)
```

**Comment by umjammer** [comment]
NSSpeechSynthesizer is deprecated
